---
- hosts: all

  tasks:
    - name: disable selinux 
      template: src=templates/selinux dest=/etc/selinux/config

    - name: Fix ssh daemon 
      template: src=templates/sshd_config dest=/etc/ssh/sshd_config

    - name: Copy bashrc 
      template: src=templates/bashrc dest=/root/.bashrc

    - name: Copy yum.conf 
      template: src=templates/yum.conf dest=/etc/yum.conf
      
    - name: add line to crontab for updatedb
      cron: name="run updatedb" minute="15" job="updatedb"

    - name: ensure telnet installed 
      yum: pkg=telnet state=installed

    - name: ensure mlocate installed 
      yum: pkg=mlocate state=installed

    - name: ensure git installed 
      yum: pkg=git state=installed

    - name: ensure tcpdump installed 
      yum: pkg=tcpdump state=installed

    - name: ensure wget installed 
      yum: pkg=wget state=installed

    - name: disable selinux
      action: command echo 0 > /selinux/enforce



